"use strict";
let kids = new Array();
kids.push("Natalie");
kids.push("Brittany");
kids.push("Zachary");
let kids2 = new Array();
kids2.push("Natalie");
kids2.push("Brittany");
let kids3 = new Array();
kids3.push("Natalie");
kids3.push("Brittany");
let kids4 = new Array();
kids4.push("Natalie");
kids4.push("Brittany");
